
const API_SERVER_HOSTNAME = process.env.NODE_ENV === 'production' ? '47.92.164.250' : 'localhost'
const API_SERVER_PROTOCOL = 'http'
const API_SERVER_PORT = 3000
const API_SERVER_HOST = `${API_SERVER_HOSTNAME}:${API_SERVER_PORT}`
const API_SERVER = `${API_SERVER_PROTOCOL}://${API_SERVER_HOST}`

console.log(process.env.NODE_ENV, 111)

module.exports = {
  API_SERVER_HOSTNAME,
  API_SERVER_PROTOCOL,
  API_SERVER_PORT,
  API_SERVER_HOST,
  API_SERVER
}