
const API_TARGET_HOSTNAME = 'easy-mock.com'
const API_TARGET_PROTOCOL = 'https'
const API_TARGET_PORT = 443
const API_TARGET_HOST = `${API_TARGET_HOSTNAME}:${API_TARGET_PORT}`
const API_TARGET = `${API_TARGET_PROTOCOL}://${API_TARGET_HOST}`

module.exports = {
  API_TARGET_HOSTNAME,
  API_TARGET_PROTOCOL,
  API_TARGET_PORT,
  API_TARGET_HOST,
  API_TARGET
}